article/urls.py
from django.urls import path, include
from . import views
from rest_framework import routers

router = routers.DefaultRouter()
router.register(r'articles', views.ArticleViewSet)
urlpatterns = [
    path('', views.index, name='index'),
    path('list/', views.ArticleListView.as_view(), name='articles'),
    path('<int:pk>', views.ArticleDetailView.as_view(), name='article-detail'),
    path('api/', include(router.urls))

    #path('articles/<int:pk>', views.BookDetailView.as_view(), name='article-detail'),
]

myblog/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('articles/', include('article.urls')),
    path('api/articles/', include('article.api_urls')),
    path('auth/', include('rest_framework.urls')),
    path('', RedirectView.as_view(url='articles/')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

article/models.py
from django.db import models
from django.urls import reverse  # Cette fonction est utilisée pour formater les URL


class Category(models.Model):
    """Cet objet représente une catégorie ou un genre littéraire."""
    name = models.CharField(max_length=200, help_text='Enter an article category (ex : Actualité)')
    image_url = models.CharField(max_length=2048, help_text='Enter an image url for the category', null=True,
                                 blank=True)

    def __str__(self):
        """Cette fonction est obligatoirement requise par Django.
           Elle retourne une chaîne de caractère pour identifier l'instance de la classe d'objet."""
        return self.name


class Article(models.Model):
    title = models.CharField(max_length=200)
    summary = models.TextField(max_length=1000, help_text='Enter a brief description of the article')
    content = models.TextField(help_text='Enter the article content')
    slug = models.CharField(max_length=300,help_text='Enter the article slug')
    cover_image_url = models.CharField(max_length=2048, help_text='Enter an image url for the article')
    created_at = models.DateTimeField(auto_now_add=True, null=True)
    updated_at = models.DateTimeField(auto_now=True, null=True)
    publish_time = models.DateTimeField(null=True,help_text='Publication date of the article')

    category = models.ForeignKey(Category, help_text='Select a category for this article', on_delete=models.SET_NULL,
                                 null=True)

    def __str__(self):
        """Fonction requise par Django pour manipuler les objets Book dans la base de données."""
        return self.title

    def get_absolute_url(self):
        """Cette fonction est requise pas Django, lorsque vous souhaitez détailler le contenu d'un objet."""
        return reverse('article-detail', args=[str(self.id)])

article/views.py
from django.shortcuts import render

from article.models import Article, Category

from django.views import generic

from django.shortcuts import get_object_or_404

from rest_framework import viewsets

from .serializers import ArticleSerializer


class ArticleViewSet(viewsets.ModelViewSet):
    queryset = Article.objects.all().order_by('title')
    serializer_class = ArticleSerializer


def article_detail_view(request, primary_key):
    article = get_object_or_404(Article, pk=primary_key)
    return render(request, 'article_detail.html', context={'article': article})



class ArticleListView(generic.ListView):
    model = Article
    template_name = 'articles.html'


class ArticleDetailView(generic.DetailView):
    model = Article
    template_name = 'article_detail.html'



def index(request):
    """View function for home page of site."""

    num_articles = Article.objects.all().count()
    num_categories = Category.objects.all().count()
    articles = Article.objects.all()

    context = {
        'num_articles': num_articles,
        'num_categories': num_categories,
        'articles_list': articles
    }

    return render(request, 'index.html', context=context)

article/templates/article_detail.html
{% extends "base_generic.html" %}

{% block content %}
<div>


    <h1>{{article.title}}({{article.category.name}})</h1>

    <small>{{article.summary}}</small>
<p>
        <img width="300px" height="auto" src="{{article.cover_image_url}}">

</p>

    <p style="padding-top:20px">{{article.content}}</p>

</div>
{% endblock %}

article/templates/articles.html
{% extends "base_generic.html" %}

{% block content %}
<div>
  <h1>Liste des articles</h1>

  <ul>

    {% for article in article_list %}

    <li><a href="{% url 'article-detail' article.pk %}"> {{article.title}}</a> </li>

    {% endfor %}

  </ul>

</div>
{% endblock %}

article/templates/base_generic.html
<!DOCTYPE html>
<html lang="en">
<head>
  {% block title %}<title>Mon blog</title>{% endblock %}
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
        integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
  <!-- Add additional CSS in static file -->
  {% load static %}
  <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>
<body>
  <div class="container-fluid">
    <div class="row">
      <div class="col-sm-2">
          {% block sidebar %}
           <ul class="sidebar-nav">
               <li><a href="{% url 'index' %}">Home</a></li>
               <li><a href="{% url 'articles' %}">Tous les Articles</a></li>
               <li><a href="">Touts les Catégories</a></li>
           </ul>
          {% endblock %}
      </div>
         <div class="col-sm-10 ">
             {% block content %}
             {% endblock %}
         </div>
    </div>
  </div>
</body>
</html>

article/templates/index.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Accueil de Mon Blog</h1>
  <p>Bienvenue dans mon Blog !</p>
  <h2>Contenu dynamique</h2>
  <p>Le Blog dispose des enregistrements suivants:</p>
  <ul>
    <li><strong>Articles:</strong> {{ num_articles }}</li>
    <li><strong>Categories:</strong> {{ num_categories }}</li>
  </ul>
<div>
  <h2>Liste des articles</h2>

  <ul>

    {% for article in articles_list %}

    <li> {{article.title}} </li>

    {% endfor %}

  </ul>

</div>
{% endblock %}